### ISSUE TITLE
Feature wish: document the functions `constrain`, `restriction` and `restrict`

### ISSUE THREAD

**Issue by claudemarche** [backtracking/ocaml-bdd#2]
Hello,

I wonder if the functions `constrain`, `restriction` or `restrict` may answer a need I have. There are not documented though, could you please add appropriate explanations of their respective behaviors in `bdd.mli` ?

**Comment by backtracking** [comment]
These three functions were contributed by @tbrk but indeed are not documented.
@tbrk Could you be kind enough to add a few sentences in `bdd.mli` to document these three functions?

**Comment by backtracking** [comment]
Thanks @tbrk !
